### Raw Data Cleaning

In [161]:
import pandas as pd

In [162]:
locations_df = pd.read_csv("../data/locations.csv")
providers_df = pd.read_csv("../data/providers.csv")
payers_df = pd.read_csv("../data/payers.csv")
patients_df = pd.read_csv("../data/patients.csv")
calls_df = pd.read_csv("../data/calls.csv")
appointments_df = pd.read_csv("../data/appointments.csv")

for name, df in [("locations", locations_df), ("providers", providers_df),
                  ("payers", payers_df), ("patients", patients_df),
                  ("calls", calls_df), ("appointments", appointments_df)]:
    print(name, df.shape)

locations (4, 4)
providers (8, 5)
payers (6, 3)
patients (9439, 4)
calls (28493, 6)
appointments (64534, 12)

### Appointments

In [163]:
appointments_df.head()

,appointment_id,date,booked_date,provider_id,location_id,patient_id,payer_id,appointment_type,is_new_patient,status,revenue,rvu
0,A1,2023-08-01,2023-07-23,P1,L1,PT1,PY1,Follow-up,False,Completed,92.03,0.93
1,A2,2023-08-01,2023-07-27,P1,L1,PT1,PY1,Physical Therapy,False,Cancelled,0.00,0.00
2,A3,2023-08-01,2023-08-01,P1,L1,PT1,PY1,Post-Op Check,False,Completed,75.98,0.57
3,A4,2023-08-01,2023-07-26,P1,L1,PT1,PY1,Follow-up,False,Completed,130.28,0.68
4,A5,2023-08-01,2023-07-30,P1,L1,PT1,PY1,Follow-up,False,Completed,137.98,1.03

In [164]:
appointments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64534 entries, 0 to 64533
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appointment_id    64534 non-null  object
 1   date              64534 non-null  object
 2   booked_date       64534 non-null  object
 3   provider_id       64534 non-null  object
 4   location_id       64534 non-null  object
 5   patient_id        64534 non-null  object
 6   payer_id          64534 non-null  object
 7   appointment_type  64534 non-null  object
 8   is_new_patient    64534 non-null  bool
 9   status            64534 non-null  object
 10  revenue           64012 non-null  float64
 11  rvu               64534 non-null  float64
dtypes: bool(1), float64(2), object(9)
memory usage: 5.5+ MB

In [165]:
# Convert dates to datetime format
appointments_df['date'] = pd.to_datetime(appointments_df['date'], errors='coerce', format='%Y-%m-%d')
appointments_df['booked_date'] = pd.to_datetime(appointments_df['booked_date'], errors='coerce', format='%Y-%m-%d')

In [166]:
# Clean column names by stripping whitespace and converting to lowercase
appointments_df.columns = appointments_df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
appointments_df.columns.tolist()

['appointment_id',
 'date',
 'booked_date',
 'provider_id',
 'location_id',
 'patient_id',
 'payer_id',
 'appointment_type',
 'is_new_patient',
 'status',
 'revenue',
 'rvu']

In [167]:
appointments_df.isna().sum()

appointment_id        0
date                  0
booked_date           0
provider_id           0
location_id           0
patient_id            0
payer_id              0
appointment_type      0
is_new_patient        0
status                0
revenue             522
rvu                   0
dtype: int64

In [168]:
blank_revenue_df = appointments_df[(appointments_df['revenue'].isna()) & (appointments_df['status'] == 'Completed')]
blank_revenue_df.shape

(522, 12)

In [169]:
appointments_df[(appointments_df['revenue'] == 0) & (appointments_df['status'] == 'Completed')]

Empty DataFrame
Columns: [appointment_id, date, booked_date, provider_id, location_id, patient_id, payer_id, appointment_type, is_new_patient, status, revenue, rvu]
Index: []

In [170]:
bad_dates = appointments_df['booked_date'] > appointments_df['date']
appointments_df.loc[bad_dates, 'booked_date'] = pd.NaT

appointments_df['booked_date'].value_counts()

booked_date
2026-07-09    111
2026-06-23    107
2025-10-31    105
2026-07-02    105
2026-02-20    104
             ...
2023-07-15      2
2023-07-12      2
2023-07-10      1
2023-07-11      1
2023-07-06      1
Name: count, Length: 1119, dtype: int64

In [195]:
appointments_df['appointment_id'].nunique() == len(appointments_df)

True

In [171]:
# Drop duplicate rows based on the 'appointment_id' column
appointments_df.drop_duplicates(subset=['appointment_id'], keep='first', inplace=True)
appointments_df.shape # 64534 -> 64213

(64213, 12)

In [172]:
set(providers_df['provider_id'])
provider_error_appointments_df = appointments_df[~appointments_df['provider_id'].isin(set(providers_df['provider_id']))]
provider_error_appointments_df

,appointment_id,date,booked_date,provider_id,location_id,patient_id,payer_id,appointment_type,is_new_patient,status,revenue,rvu
689,A690,2023-08-16,2023-08-10,P99,L2,PT67,PY3,Post-Op Check,False,Completed,87.12,0.76
1056,A1057,2023-08-24,2023-07-31,P99,L3,PT156,PY3,New Patient Consult,True,No-Show,0.00,0.00
2262,A2263,2023-09-21,2023-09-18,P99,L1,PT227,PY4,Physical Therapy,False,Completed,123.63,1.32
2883,A2884,2023-10-05,2023-10-05,P99,L1,PT33,PY5,Physical Therapy,False,Completed,124.15,1.40
3138,A3139,2023-10-10,2023-10-02,P99,L3,PT250,PY2,Follow-up,False,Completed,89.65,0.83
...,...,...,...,...,...,...,...,...,...,...,...,...
61217,A61218,2026-06-24,2026-06-12,P99,L1,PT4486,PY1,Follow-up,False,Completed,125.67,0.83
61387,A61388,2026-06-25,2026-06-24,P99,L4,PT3169,PY3,Follow-up,False,Completed,79.03,1.01
62024,A62025,2026-07-03,2026-06-18,P99,L1,PT5714,PY6,Follow-up,False,Completed,119.12,1.08
63150,A63151,2026-07-17,2026-07-06,P99,L2,PT4338,PY1,Follow-up,False,Completed,89.56,0.86
63230,A63231,2026-07-18,2026-07-04,P99,L3,PT9302,PY3,New Patient Consult,True,Completed,298.76,1.82

In [173]:
# P99 doesn't exist in providers_df, but it does exist in appointments_df. This is likely a data quality issue that needs to be addressed.
set(appointments_df['provider_id'])

{'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P99'}

In [174]:
invalid_provider_mask = ~appointments_df['provider_id'].isin(set(providers_df['provider_id']))
appointments_df.loc[invalid_provider_mask, 'provider_id'] = 'UNK'

appointments_df[appointments_df['provider_id'] == 'UNK']

,appointment_id,date,booked_date,provider_id,location_id,patient_id,payer_id,appointment_type,is_new_patient,status,revenue,rvu
689,A690,2023-08-16,2023-08-10,UNK,L2,PT67,PY3,Post-Op Check,False,Completed,87.12,0.76
1056,A1057,2023-08-24,2023-07-31,UNK,L3,PT156,PY3,New Patient Consult,True,No-Show,0.00,0.00
2262,A2263,2023-09-21,2023-09-18,UNK,L1,PT227,PY4,Physical Therapy,False,Completed,123.63,1.32
2883,A2884,2023-10-05,2023-10-05,UNK,L1,PT33,PY5,Physical Therapy,False,Completed,124.15,1.40
3138,A3139,2023-10-10,2023-10-02,UNK,L3,PT250,PY2,Follow-up,False,Completed,89.65,0.83
...,...,...,...,...,...,...,...,...,...,...,...,...
61217,A61218,2026-06-24,2026-06-12,UNK,L1,PT4486,PY1,Follow-up,False,Completed,125.67,0.83
61387,A61388,2026-06-25,2026-06-24,UNK,L4,PT3169,PY3,Follow-up,False,Completed,79.03,1.01
62024,A62025,2026-07-03,2026-06-18,UNK,L1,PT5714,PY6,Follow-up,False,Completed,119.12,1.08
63150,A63151,2026-07-17,2026-07-06,UNK,L2,PT4338,PY1,Follow-up,False,Completed,89.56,0.86
63230,A63231,2026-07-18,2026-07-04,UNK,L3,PT9302,PY3,New Patient Consult,True,Completed,298.76,1.82

In [175]:
appointments_df[~appointments_df['location_id'].isin(set(locations_df['location_id']))]

Empty DataFrame
Columns: [appointment_id, date, booked_date, provider_id, location_id, patient_id, payer_id, appointment_type, is_new_patient, status, revenue, rvu]
Index: []

In [176]:
appointments_df[~appointments_df['patient_id'].isin(set(patients_df['patient_id']))]

Empty DataFrame
Columns: [appointment_id, date, booked_date, provider_id, location_id, patient_id, payer_id, appointment_type, is_new_patient, status, revenue, rvu]
Index: []

In [177]:
appointments_df[~appointments_df['payer_id'].isin(set(payers_df['payer_id']))]

Empty DataFrame
Columns: [appointment_id, date, booked_date, provider_id, location_id, patient_id, payer_id, appointment_type, is_new_patient, status, revenue, rvu]
Index: []

In [178]:
appointments_df.shape

(64213, 12)

### Patients

In [182]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9439 entries, 0 to 9438
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   patient_id        9439 non-null   object
 1   first_visit_date  9439 non-null   object
 2   referral_source   9439 non-null   object
 3   payer_id          9439 non-null   object
dtypes: object(4)
memory usage: 295.1+ KB

In [192]:
patients_df['patient_id'].nunique() == len(patients_df)

True

In [ ]:
patients_df['first_visit_date'] = pd.to_datetime(patients_df['first_visit_date'], errors='coerce', format='%Y-%m-%d')

In [188]:
patients_df['first_visit_date'].unique()

array(['2023-08-01', '2023-08-02', '2023-08-03', '2023-08-04',
       '2023-08-05', '2023-08-07', '2023-08-08', '2023-08-09',
       '2023-08-10', '2023-08-11', '2023-08-12', '2023-08-14',
       '2023-08-15', '2023-08-16', '2023-08-17', '2023-08-18',
       '2023-08-19', '2023-08-21', '2023-08-22', '2023-08-23',
       '2023-08-24', '2023-08-25', '2023-08-26', '2023-08-28',
       '2023-08-29', '2023-08-30', '2023-08-31', '2023-09-01',
       '2023-09-02', '2023-09-04', '2023-09-05', '2023-09-06',
       '2023-09-07', '2023-09-08', '2023-09-09', '2023-09-11',
       '2023-09-12', '2023-09-13', '2023-09-14', '2023-09-15',
       '2023-09-16', '2023-09-18', '2023-09-19', '2023-09-20',
       '2023-09-21', '2023-09-22', '2023-09-23', '2023-09-25',
       '2023-09-26', '2023-09-27', '2023-09-28', '2023-09-29',
       '2023-09-30', '2023-10-02', '2023-10-03', '2023-10-04',
       '2023-10-05', '2023-10-06', '2023-10-07', '2023-10-09',
       '2023-10-10', '2023-10-11', '2023-10-12', '2023-10-13',
       '2023-10-14', '2023-10-16', '2023-10-17', '2023-10-18',
       '2023-10-19', '2023-10-20', '2023-10-21', '2023-10-23',
       '2023-10-24', '2023-10-25', '2023-10-26', '2023-10-27',
       '2023-10-28', '2023-10-30', '2023-10-31', '2023-11-01',
       '2023-11-02', '2023-11-03', '2023-11-04', '2023-11-06',
       '2023-11-07', '2023-11-08', '2023-11-09', '2023-11-10',
       '2023-11-11', '2023-11-13', '2023-11-14', '2023-11-15',
       '2023-11-16', '2023-11-17', '2023-11-18', '2023-11-20',
       '2023-11-21', '2023-11-22', '2023-11-23', '2023-11-24',
       '2023-11-25', '2023-11-27', '2023-11-28', '2023-11-29',
       '2023-11-30', '2023-12-01', '2023-12-02', '2023-12-04',
       '2023-12-05', '2023-12-06', '2023-12-07', '2023-12-08',
       '2023-12-09', '2023-12-11', '2023-12-12', '2023-12-13',
       '2023-12-14', '2023-12-15', '2023-12-16', '2023-12-18',
       '2023-12-19', '2023-12-20', '2023-12-21', '2023-12-22',
       '2023-12-23', '2023-12-25', '2023-12-26', '2023-12-27',
       '2023-12-28', '2023-12-29', '2023-12-30', '2024-01-01',
       '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05',
       '2024-01-06', '2024-01-08', '2024-01-09', '2024-01-10',
       '2024-01-11', '2024-01-12', '2024-01-13', '2024-01-15',
       '2024-01-16', '2024-01-17', '2024-01-18', '2024-01-19',
       '2024-01-20', '2024-01-22', '2024-01-23', '2024-01-24',
       '2024-01-25', '2024-01-26', '2024-01-27', '2024-01-29',
       '2024-01-30', '2024-01-31', '2024-02-01', '2024-02-02',
       '2024-02-03', '2024-02-05', '2024-02-06', '2024-02-07',
       '2024-02-08', '2024-02-09', '2024-02-10', '2024-02-12',
       '2024-02-13', '2024-02-14', '2024-02-15', '2024-02-16',
       '2024-02-17', '2024-02-19', '2024-02-20', '2024-02-21',
       '2024-02-22', '2024-02-23', '2024-02-24', '2024-02-26',
       '2024-02-27', '2024-02-28', '2024-02-29', '2024-03-01',
       '2024-03-02', '2024-03-04', '2024-03-05', '2024-03-06',
       '2024-03-07', '2024-03-08', '2024-03-09', '2024-03-11',
       '2024-03-12', '2024-03-13', '2024-03-14', '2024-03-15',
       '2024-03-16', '2024-03-18', '2024-03-19', '2024-03-20',
       '2024-03-21', '2024-03-22', '2024-03-23', '2024-03-25',
       '2024-03-26', '2024-03-27', '2024-03-28', '2024-03-29',
       '2024-03-30', '2024-04-01', '2024-04-02', '2024-04-03',
       '2024-04-04', '2024-04-05', '2024-04-06', '2024-04-08',
       '2024-04-09', '2024-04-10', '2024-04-11', '2024-04-12',
       '2024-04-13', '2024-04-15', '2024-04-16', '2024-04-17',
       '2024-04-18', '2024-04-19', '2024-04-22', '2024-04-23',
       '2024-04-24', '2024-04-25', '2024-04-26', '2024-04-27',
       '2024-04-29', '2024-04-30', '2024-05-01', '2024-05-02',
       '2024-05-03', '2024-05-04', '2024-05-06', '2024-05-07',
       '2024-05-08', '2024-05-09', '2024-05-10', '2024-05-11',
       '2024-05-13', '2024-05-14', '2024-05-15', '2024-05-16',
       '2024-05-17', '2024-05-18', '2024-05-20', '2024-05-21',
       '2024-05-22', '2024-05-23', '2024-05-24', '2024-05-25',
       '2024-05-27', '2024-05-28', '2024-05-29', '2024-05-30',
       '2024-05-31', '2024-06-01', '2024-06-03', '2024-06-04',
       '2024-06-05', '2024-06-06', '2024-06-07', '2024-06-08',
       '2024-06-10', '2024-06-11', '2024-06-12', '2024-06-13',
       '2024-06-14', '2024-06-15', '2024-06-17', '2024-06-18',
       '2024-06-19', '2024-06-20', '2024-06-21', '2024-06-22',
       '2024-06-24', '2024-06-25', '2024-06-26', '2024-06-27',
       '2024-06-28', '2024-06-29', '2024-07-01', '2024-07-02',
       '2024-07-03', '2024-07-04', '2024-07-05', '2024-07-06',
       '2024-07-08', '2024-07-09', '2024-07-10', '2024-07-11',
       '2024-07-12', '2024-07-13', '2024-07-15', '2024-07-16',
       '2024-07-17', '2024-07-18', '2024-07-19', '2024-07-20',
       '2024-07-22', '2024-07-23', '2024-07-24', '2024-07-25',
       '2024-07-26', '2024-07-27', '2024-07-29', '2024-07-30',
       '2024-07-31', '2024-08-01', '2024-08-02', '2024-08-03',
       '2024-08-05', '2024-08-06', '2024-08-07', '2024-08-08',
       '2024-08-09', '2024-08-10', '2024-08-12', '2024-08-13',
       '2024-08-14', '2024-08-15', '2024-08-16', '2024-08-17',
       '2024-08-19', '2024-08-20', '2024-08-21', '2024-08-22',
       '2024-08-23', '2024-08-24', '2024-08-26', '2024-08-27',
       '2024-08-28', '2024-08-29', '2024-08-30', '2024-08-31',
       '2024-09-02', '2024-09-03', '2024-09-04', '2024-09-05',
       '2024-09-06', '2024-09-07', '2024-09-09', '2024-09-10',
       '2024-09-11', '2024-09-12', '2024-09-13', '2024-09-14',
       '2024-09-16', '2024-09-17', '2024-09-18', '2024-09-19',
       '2024-09-20', '2024-09-21', '2024-09-23', '2024-09-24',
       '2024-09-25', '2024-09-26', '2024-09-27', '2024-09-28',
       '2024-09-30', '2024-10-01', '2024-10-02', '2024-10-03',
       '2024-10-04', '2024-10-05', '2024-10-07', '2024-10-08',
       '2024-10-09', '2024-10-10', '2024-10-11', '2024-10-12',
       '2024-10-14', '2024-10-15', '2024-10-16', '2024-10-17',
       '2024-10-18', '2024-10-19', '2024-10-21', '2024-10-22',
       '2024-10-23', '2024-10-24', '2024-10-25', '2024-10-26',
       '2024-10-28', '2024-10-29', '2024-10-30', '2024-10-31',
       '2024-11-01', '2024-11-02', '2024-11-04', '2024-11-05',
       '2024-11-06', '2024-11-07', '2024-11-08', '2024-11-09',
       '2024-11-11', '2024-11-12', '2024-11-13', '2024-11-14',
       '2024-11-15', '2024-11-16', '2024-11-18', '2024-11-19',
       '2024-11-20', '2024-11-21', '2024-11-22', '2024-11-23',
       '2024-11-25', '2024-11-26', '2024-11-27', '2024-11-28',
       '2024-11-29', '2024-11-30', '2024-12-02', '2024-12-03',
       '2024-12-04', '2024-12-05', '2024-12-06', '2024-12-07',
       '2024-12-09', '2024-12-10', '2024-12-11', '2024-12-12',
       '2024-12-13', '2024-12-14', '2024-12-16', '2024-12-17',
       '2024-12-18', '2024-12-19', '2024-12-20', '2024-12-21',
       '2024-12-23', '2024-12-24', '2024-12-25', '2024-12-26',
       '2024-12-27', '2024-12-28', '2024-12-30', '2024-12-31',
       '2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
       '2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09',
       '2025-01-10', '2025-01-11', '2025-01-13', '2025-01-14',
       '2025-01-15', '2025-01-16', '2025-01-17', '2025-01-18',
       '2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23',
       '2025-01-24', '2025-01-25', '2025-01-27', '2025-01-28',
       '2025-01-29', '2025-01-30', '2025-01-31', '2025-02-01',
       '2025-02-03', '2025-02-04', '2025-02-05', '2025-02-06',
       '2025-02-07', '2025-02-08', '2025-02-10', '2025-02-11',
       '2025-02-12', '2025-02-13', '2025-02-14', '2025-02-15',
       '2025-02-17', '2025-02-18', '2025-02-19', '2025-02-20',
       '2025-02-21', '2025-02-22', '2025-02-24', '2025-02-25',
       '2025-02-26', '2025-02-27', '2025-02-28', '2025-03-01',
       '2025-03-03', '2025-03-04', '2025-03-05', '2025-03-06',
       '2025-03-07', '2025-03-08', '2025-03-10', '2025-03-11',
       '2025-03-12', '2025-03-13', '2025-03-14', '2025-03-15',
       '2025-03-17', '2025-03-18', '2025-03-19', '2025-03-20',
       '2025-03-21', '2025-03-22', '2025-03-24', '2025-03-25',
       '2025-03-26', '2025-03-27', '2025-03-28', '2025-03-29',
       '2025-03-31', '2025-04-01', '2025-04-02', '2025-04-03',
       '2025-04-04', '2025-04-05', '2025-04-07', '2025-04-08',
       '2025-04-09', '2025-04-10', '2025-04-11', '2025-04-12',
       '2025-04-14', '2025-04-15', '2025-04-16', '2025-04-17',
       '2025-04-18', '2025-04-19', '2025-04-21', '2025-04-22',
       '2025-04-23', '2025-04-24', '2025-04-25', '2025-04-26',
       '2025-04-28', '2025-04-29', '2025-04-30', '2025-05-01',
       '2025-05-02', '2025-05-03', '2025-05-05', '2025-05-06',
       '2025-05-07', '2025-05-08', '2025-05-09', '2025-05-10',
       '2025-05-12', '2025-05-13', '2025-05-14', '2025-05-15',
       '2025-05-16', '2025-05-19', '2025-05-20', '2025-05-21',
       '2025-05-22', '2025-05-23', '2025-05-24', '2025-05-26',
       '2025-05-27', '2025-05-28', '2025-05-29', '2025-05-30',
       '2025-05-31', '2025-06-02', '2025-06-03', '2025-06-04',
       '2025-06-05', '2025-06-06', '2025-06-07', '2025-06-09',
       '2025-06-10', '2025-06-11', '2025-06-12', '2025-06-13',
       '2025-06-14', '2025-06-16', '2025-06-17', '2025-06-18',
       '2025-06-19', '2025-06-20', '2025-06-21', '2025-06-23',
       '2025-06-24', '2025-06-25', '2025-06-26', '2025-06-27',
       '2025-06-28', '2025-06-30', '2025-07-01', '2025-07-02',
       '2025-07-03', '2025-07-04', '2025-07-07', '2025-07-08',
       '2025-07-09', '2025-07-10', '2025-07-11', '2025-07-12',
       '2025-07-14', '2025-07-15', '2025-07-16', '2025-07-17',
       '2025-07-18', '2025-07-19', '2025-07-21', '2025-07-22',
       '2025-07-23', '2025-07-24', '2025-07-25', '2025-07-26',
       '2025-07-28', '2025-07-29', '2025-07-30', '2025-07-31',
       '2025-08-01', '2025-08-02', '2025-08-04', '2025-08-05',
       '2025-08-06', '2025-08-07', '2025-08-08', '2025-08-09',
       '2025-08-11', '2025-08-12', '2025-08-13', '2025-08-14',
       '2025-08-15', '2025-08-16', '2025-08-18', '2025-08-19',
       '2025-08-20', '2025-08-21', '2025-08-22', '2025-08-23',
       '2025-08-25', '2025-08-26', '2025-08-27', '2025-08-28',
       '2025-08-29', '2025-08-30', '2025-09-01', '2025-09-02',
       '2025-09-03', '2025-09-04', '2025-09-05', '2025-09-06',
       '2025-09-08', '2025-09-09', '2025-09-10', '2025-09-11',
       '2025-09-12', '2025-09-13', '2025-09-15', '2025-09-16',
       '2025-09-17', '2025-09-18', '2025-09-19', '2025-09-20',
       '2025-09-22', '2025-09-23', '2025-09-24', '2025-09-25',
       '2025-09-26', '2025-09-27', '2025-09-29', '2025-09-30',
       '2025-10-01', '2025-10-02', '2025-10-03', '2025-10-04',
       '2025-10-06', '2025-10-07', '2025-10-08', '2025-10-09',
       '2025-10-10', '2025-10-11', '2025-10-13', '2025-10-14',
       '2025-10-15', '2025-10-16', '2025-10-17', '2025-10-18',
       '2025-10-20', '2025-10-21', '2025-10-22', '2025-10-23',
       '2025-10-24', '2025-10-25', '2025-10-27', '2025-10-28',
       '2025-10-29', '2025-10-30', '2025-10-31', '2025-11-01',
       '2025-11-03', '2025-11-04', '2025-11-05', '2025-11-06',
       '2025-11-07', '2025-11-08', '2025-11-10', '2025-11-11',
       '2025-11-12', '2025-11-13', '2025-11-14', '2025-11-15',
       '2025-11-17', '2025-11-18', '2025-11-19', '2025-11-20',
       '2025-11-21', '2025-11-22', '2025-11-24', '2025-11-25',
       '2025-11-26', '2025-11-27', '2025-11-28', '2025-11-29',
       '2025-12-01', '2025-12-02', '2025-12-03', '2025-12-04',
       '2025-12-05', '2025-12-06', '2025-12-08', '2025-12-09',
       '2025-12-10', '2025-12-11', '2025-12-12', '2025-12-15',
       '2025-12-16', '2025-12-17', '2025-12-18', '2025-12-19',
       '2025-12-20', '2025-12-22', '2025-12-23', '2025-12-24',
       '2025-12-25', '2025-12-26', '2025-12-27', '2025-12-29',
       '2025-12-30', '2025-12-31', '2026-01-01', '2026-01-02',
       '2026-01-03', '2026-01-05', '2026-01-06', '2026-01-07',
       '2026-01-08', '2026-01-09', '2026-01-10', '2026-01-12',
       '2026-01-13', '2026-01-14', '2026-01-15', '2026-01-16',
       '2026-01-17', '2026-01-19', '2026-01-20', '2026-01-21',
       '2026-01-22', '2026-01-23', '2026-01-24', '2026-01-26',
       '2026-01-27', '2026-01-28', '2026-01-29', '2026-01-30',
       '2026-01-31', '2026-02-02', '2026-02-03', '2026-02-04',
       '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-09',
       '2026-02-10', '2026-02-11', '2026-02-12', '2026-02-13',
       '2026-02-14', '2026-02-16', '2026-02-17', '2026-02-18',
       '2026-02-19', '2026-02-20', '2026-02-21', '2026-02-23',
       '2026-02-24', '2026-02-25', '2026-02-26', '2026-02-27',
       '2026-02-28', '2026-03-02', '2026-03-03', '2026-03-04',
       '2026-03-05', '2026-03-06', '2026-03-07', '2026-03-09',
       '2026-03-10', '2026-03-11', '2026-03-12', '2026-03-13',
       '2026-03-14', '2026-03-16', '2026-03-17', '2026-03-18',
       '2026-03-19', '2026-03-20', '2026-03-21', '2026-03-23',
       '2026-03-24', '2026-03-25', '2026-03-26', '2026-03-27',
       '2026-03-28', '2026-03-30', '2026-03-31', '2026-04-01',
       '2026-04-02', '2026-04-03', '2026-04-04', '2026-04-06',
       '2026-04-07', '2026-04-08', '2026-04-09', '2026-04-10',
       '2026-04-11', '2026-04-13', '2026-04-14', '2026-04-15',
       '2026-04-16', '2026-04-17', '2026-04-18', '2026-04-20',
       '2026-04-21', '2026-04-22', '2026-04-23', '2026-04-24',
       '2026-04-25', '2026-04-27', '2026-04-28', '2026-04-29',
       '2026-04-30', '2026-05-01', '2026-05-02', '2026-05-04',
       '2026-05-05', '2026-05-06', '2026-05-07', '2026-05-08',
       '2026-05-09', '2026-05-11', '2026-05-12', '2026-05-13',
       '2026-05-14', '2026-05-15', '2026-05-16', '2026-05-18',
       '2026-05-19', '2026-05-20', '2026-05-21', '2026-05-22',
       '2026-05-23', '2026-05-25', '2026-05-26', '2026-05-27',
       '2026-05-28', '2026-05-29', '2026-05-30', '2026-06-01',
       '2026-06-02', '2026-06-03', '2026-06-04', '2026-06-05',
       '2026-06-06', '2026-06-08', '2026-06-09', '2026-06-10',
       '2026-06-11', '2026-06-12', '2026-06-13', '2026-06-15',
       '2026-06-16', '2026-06-17', '2026-06-18', '2026-06-19',
       '2026-06-20', '2026-06-22', '2026-06-23', '2026-06-24',
       '2026-06-25', '2026-06-26', '2026-06-27', '2026-06-29',
       '2026-06-30', '2026-07-01', '2026-07-02', '2026-07-03',
       '2026-07-04', '2026-07-06', '2026-07-07', '2026-07-08',
       '2026-07-09', '2026-07-10', '2026-07-11', '2026-07-13',
       '2026-07-14', '2026-07-15', '2026-07-16', '2026-07-17',
       '2026-07-18', '2026-07-20', '2026-07-21', '2026-07-22',
       '2026-07-23', '2026-07-24', '2026-07-25', '2026-07-27',
       '2026-07-28', '2026-07-29', '2026-07-30', '2026-07-31'],
      dtype=object)

In [183]:
patients_df.head()

  patient_id first_visit_date      referral_source payer_id
0        PT1       2023-08-01        Friend/Family      PY1
1        PT2       2023-08-01  Insurance Directory      PY2
2        PT3       2023-08-01        Friend/Family      PY3
3        PT4       2023-08-01   Physician Referral      PY6
4        PT5       2023-08-01   Physician Referral      PY1

In [189]:
patients_df['referral_source'].unique()

array(['Friend/Family', 'Insurance Directory', 'Physician Referral',
       'Online Search', 'Self', 'Physician referral ', ' Self ',
       'physician referral', 'self', 'SELF'], dtype=object)

In [190]:
patients_df['referral_source'] = patients_df['referral_source'].str.strip().str.title()

In [191]:
patients_df['referral_source'].unique()

array(['Friend/Family', 'Insurance Directory', 'Physician Referral',
       'Online Search', 'Self'], dtype=object)

In [196]:
# No errors
invalid_payer_mask = ~patients_df['payer_id'].isin(set(payers_df['payer_id']))
patients_df[invalid_payer_mask]

Empty DataFrame
Columns: [patient_id, first_visit_date, referral_source, payer_id]
Index: []

In [ ]:
# Nothing dropped
patients_df.drop_duplicates()

     patient_id first_visit_date      referral_source payer_id
0           PT1       2023-08-01        Friend/Family      PY1
1           PT2       2023-08-01  Insurance Directory      PY2
2           PT3       2023-08-01        Friend/Family      PY3
3           PT4       2023-08-01   Physician Referral      PY6
4           PT5       2023-08-01   Physician Referral      PY1
...         ...              ...                  ...      ...
9434     PT9435       2026-07-31        Online Search      PY1
9435     PT9436       2026-07-31        Friend/Family      PY3
9436     PT9437       2026-07-31        Friend/Family      PY1
9437     PT9438       2026-07-31  Insurance Directory      PY3
9438     PT9439       2026-07-31  Insurance Directory      PY5

[9439 rows x 4 columns]