In [1]:
import pandas as pd

In [6]:
appointments_df = pd.read_csv('../data/appointments.csv')
appointments_df.head(20)

,appointment_id,date,booked_date,provider_id,location_id,patient_id,payer_id,appointment_type,is_new_patient,status,revenue,rvu
0,A1,2023-08-01,2023-07-23,P1,L1,PT1,PY1,Follow-up,False,Completed,92.03,0.93
1,A2,2023-08-01,2023-07-27,P1,L1,PT1,PY1,Physical Therapy,False,Cancelled,0.00,0.00
2,A3,2023-08-01,2023-08-01,P1,L1,PT1,PY1,Post-Op Check,False,Completed,75.98,0.57
3,A4,2023-08-01,2023-07-26,P1,L1,PT1,PY1,Follow-up,False,Completed,130.28,0.68
4,A5,2023-08-01,2023-07-30,P1,L1,PT1,PY1,Follow-up,False,Completed,137.98,1.03
5,A6,2023-08-01,2023-07-20,P1,L1,PT1,PY1,Post-Op Check,False,Completed,73.61,0.59
6,A7,2023-08-01,2023-07-27,P1,L1,PT1,PY1,Post-Op Check,False,Completed,64.26,0.69
7,A8,2023-08-01,2023-08-01,P1,L1,PT1,PY1,Follow-up,False,Cancelled,0.00,0.00
8,A9,2023-08-01,2023-07-26,P1,L1,PT1,PY1,Follow-up,False,Completed,104.20,0.66
9,A10,2023-08-01,2023-07-19,P1,L4,PT1,PY1,Injection/Procedure,False,Completed,334.31,3.63
10,A11,2023-08-01,2023-07-27,P2,L1,PT1,PY1,Follow-up,False,No-Show,0.00,0.00
11,A12,2023-08-01,2023-07-28,P2,L1,PT1,PY1,Physical Therapy,False,Completed,155.02,1.28
12,A13,2023-08-01,2023-08-01,P3,L1,PT1,PY1,Post-Op Check,False,Completed,80.70,0.54
13,A14,2023-08-01,2023-07-15,P3,L1,PT1,PY1,Follow-up,False,Completed,70.50,0.95
14,A15,2023-08-01,2023-08-02,P3,L1,PT2,PY2,New Patient Consult,True,Completed,198.52,2.55
15,A16,2023-08-01,2023-07-28,P3,L1,PT2,PY2,Follow-up,False,Completed,83.33,0.65
16,A17,2023-08-01,2023-07-25,P3,L1,PT1,PY1,Post-Op Check,False,No-Show,0.00,0.00
17,A18,2023-08-01,2023-07-27,P3,L1,PT1,PY1,Physical Therapy,False,Completed,103.31,1.12
18,A19,2023-08-01,2023-07-23,P3,L1,PT2,PY2,Physical Therapy,False,Completed,149.92,0.95
19,A20,2023-08-01,2023-07-27,P3,L1,PT1,PY1,Follow-up,False,Completed,134.85,1.02

In [7]:
appointments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64534 entries, 0 to 64533
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appointment_id    64534 non-null  object
 1   date              64534 non-null  object
 2   booked_date       64534 non-null  object
 3   provider_id       64534 non-null  object
 4   location_id       64534 non-null  object
 5   patient_id        64534 non-null  object
 6   payer_id          64534 non-null  object
 7   appointment_type  64534 non-null  object
 8   is_new_patient    64534 non-null  bool
 9   status            64534 non-null  object
 10  revenue           64012 non-null  float64
 11  rvu               64534 non-null  float64
dtypes: bool(1), float64(2), object(9)
memory usage: 5.5+ MB

In [8]:
# Convert dates to datetime format
appointments_df['date'] = pd.to_datetime(appointments_df['date'], errors='coerce', format='%Y-%m-%d')
appointments_df['booked_date'] = pd.to_datetime(appointments_df['booked_date'], errors='coerce', format='%Y-%m-%d')

In [ ]:
# Clean column names by stripping whitespace and converting to lowercase
appointments_df.columns = appointments_df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
appointments_df.columns.tolist()

In [12]:
appointments_df.isna().sum()

appointment_id        0
date                  0
booked_date           0
provider_id           0
location_id           0
patient_id            0
payer_id              0
appointment_type      0
is_new_patient        0
status                0
revenue             522
rvu                   0
dtype: int64

In [17]:
blank_revenue_mask = appointments_df[appointments_df['revenue'].isna() & appointments_df['status'] == 'Completed']
blank_revenue_mask

Empty DataFrame
Columns: [appointment_id, date, booked_date, provider_id, location_id, patient_id, payer_id, appointment_type, is_new_patient, status, revenue, rvu]
Index: []

In [16]:
appointments_df[(appointments_df['revenue'] == 0) & (appointments_df['status'] == 'Completed')]

Empty DataFrame
Columns: [appointment_id, date, booked_date, provider_id, location_id, patient_id, payer_id, appointment_type, is_new_patient, status, revenue, rvu]
Index: []

In [ ]:
# Drop duplicate rows based on the 'appointment_id' column
appointments_df.drop_duplicates(subset=['appointment_id'], keep='first', inplace=True)
appointments_df.shape # 64534 -> 64140

(64140, 12)